### ISSUE TITLE
Problem regex GIT_CLEAN_REGEX 

### ISSUE THREAD

**Issue by marcelolucio1982** [mrkmg/node-generate-release#27]
Good night, I can not say if it could be considered a bug, but always I run the command to generate the release, the error message was displayed: 'Working directory is not clean, not ready for release'

I noticed that installing git on ubuntu via apt-get translated the reply messages into my language.

So the regex did not work. I changed the regex and everything worked perfectly.

Excellent project

**Comment by mrkmg** [comment]
I just pushed a more permanent fix for this. No longer uses regex to determine if the working directory is clean.
