### ISSUE TITLE
Release command fails

### ISSUE THREAD

**Issue by steffans** [mrkmg/node-generate-release#3]
I just tried to generate a release however, the package.json gets not updated or commited and i get this error message. Any suggestions?

![err](https://cloud.githubusercontent.com/assets/321013/16521688/d39afe00-3f98-11e6-943b-d7d1bedebf89.png)

**Comment by mrkmg** [comment]
What version of GIT are you using? How did you invoke generate-release?

**Comment by steffans** [comment]
I am on a Mac latest OSX, GIT 2.8.3, heres my test setup https://github.com/steffans/test-release/tree/develop

`npm run release` to run the script.

**Comment by mrkmg** [comment]
After running a couple tests, this may be related to: https://github.com/nvie/gitflow/issues/98 but I am not completely sure because I am getting different error. Doing more testing.

**Comment by steffans** [comment]
Thanx, does my test work for you? I also wonder why the message has no quotes in the command.

`release finish -m Release 0.0.2 0.0.2` 

should be

`release finish -m "Release 0.0.2" 0.0.2`

**Comment by mrkmg** [comment]
@steffans  Could you please try installed the gnu-getopts and let me know i the problem still persists?

https://github.com/petervanderdoes/gitflow-avh/wiki/Installing-on-Mac-OS-X#post-installation-setup-1

**Comment by mrkmg** [comment]
I just had a successful run on OSX. Please check the updated README for the OSX notes and install git-flow-avh with gnu-getopts.

**Comment by steffans** [comment]
Thank you! I checked my git flow install, i used the `git-flow` port. I uninstalled this port and switched to latest `git-flow-avh` which works even without `gnu-getopts`

**Comment by steffans** [comment]
@mrkmg Can you check if there are quotes missing the `release finish -m Release 0.0.2 0.0.2` command? The message should be only `Release 0.0.2` right? 

![bildschirmfoto 2016-07-03 um 18 20 37](https://cloud.githubusercontent.com/assets/321013/16546457/177b8118-414b-11e6-8338-243b87437751.png)

**Comment by mrkmg** [comment]
The quotes shouldn't be the problem as I am using [spawnSync](https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options) to spawn the git process and pass the arguments.

I am going to build in a test proper setting of the release message. Once I have that done I will report back what I am seeing on OSX.

**Comment by mrkmg** [comment]
I don't have a mac to test on. Can you manually start a release, then finish one with the -m flag and see if the commit message is correct?

**Comment by steffans** [comment]
Ok done, i have run: `git flow release finish 0.1.2 -m 'Release message'`

![bildschirmfoto 2016-07-03 um 21 33 08](https://cloud.githubusercontent.com/assets/321013/16547209/c8396dde-4165-11e6-9e34-a8ef3e9d9b62.png)

It seems like the version number gets automatically prepended to the release message.

**Comment by mrkmg** [comment]
So I borrow a mac and I got different results. Looking at the source of git-flow-avh now to try to understand what is going on...

**Comment by mrkmg** [comment]
Okay, so I think I have this resolved. generate-release now detects if you are using the AVH edition, and uses the -f flag to pass the release message. I still recommend that gnu-getopts is installed as on Mac I tested on I was getting problems unless I installed it. I am seeing the correct release message in my tests now and this should be available in version 0.9.0

Please let me know if you are still seeing a problem after the 0.9.0 release. I will close this now, but if you are still having an issue, I will re-open.

**Comment by steffans** [comment]
@mrkmg Thanks, i will try it.
