### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by steffans** [mrkmg/node-generate-release#4]
After using the `generate-relase` module here are some ideas and features which would be nice to have 😉 

Instead of creating an extra file `.release.json` it would be nice put options in the `config` of the `package.json`.
```js
{
  config: {
    release: {
      no_confirm: false,
      skip_git_pull: false,
      skip_git_push: false,
      // etc ...
    }
  }
}
```

It would be cool to have a option to set your own default release message.
```js
release_message: "My release message for {version}"
```

**Comment by mrkmg** [comment]
I like the release_message idea. I will add this to the todo.

For the first idea, I want the module to work outside of npm based projects. In fact, I recently added a section to the readme explaining how to use in other projects.

**Comment by steffans** [comment]
Sure makes sense to use it in projects without a package.json. However using the `config` from the package.json could be also supported. I usually define some `scripts` and i would be nice to define `pre_commit_commands` in the same place.

**Comment by mrkmg** [comment]
I see. Maybe a cli flag to set the pre_commit_commands. I have seen other programs that can accept an array as a key.

    generate-release --pre-commit-commands "'command 1','command 2'"

Another option would be an argument that directs generate-release to look for a key inside a json file and start there. For example we could have:

    generate-release --release-file-key release

and then in the package.json file have:

    ...
    "release": {
        "pre_commit_commands": ["..."]
    },
    ...

Thoughts?

**Comment by mrkmg** [comment]
Another option for the cli argument, would be to have a repeatable option, like:

    generate-release --pre-commit-command "command 1" --pre-commit-command "command 2"

**Comment by steffans** [comment]
I like second option, this would mean my package.json would look like this.

```js
{
  "name": "test",
  "version": "0.1.1",
  "scripts": {
    "release": "generate-release --release-file ./package.json --release-file-key release"
  },
  "release": {
    "no_confirm": false,
    "skip_git_pull": false,
    "skip_git_push": false,
    // etc ...
  }
  "devDependencies": {
    "generate-release": "^0.7.6"
  }
}
```
Maybe the `release-file-key` option can default to `release` and will be only used when the `release-file` differs from `.release.json`.

**Comment by mrkmg** [comment]
I have made it so you can now have a template for the release message. Still thinking about how to integrate the .release.json file into the package.json in an extendable way.

**Comment by mrkmg** [comment]
I have added the ability to define the options in the package.json file. See the updates readme.

I decided I would just add in a special case for those using an NPM package.json file. If you have the properties in the config : generateRelease section you will be all set.
