### ISSUE TITLE
git-flow versiontag

### ISSUE THREAD

**Issue by matt328** [mrkmg/node-generate-release#5]
If I specify a versiontag in my git-flow options, I have noticed two issues:

1. The versiontag is prepended to the version written into my package.json.  I don't think that should be.
2. The tag created in git has the versiontag prepended twice.  ex: if my versiontag is 'REL-', my git tags look like 'REL-REL-x.x.x'.  I don't think this should be either, it is probably a side effect of prepending the versiontag and putting that value in options.next_version.

**Comment by matt328** [comment]
After looking at this some more, I'm not sure if node-generate-release should even care bother reading the versiontag property, provided of course that the current behavior of prepending it in package.json is not intended.  git-flow will append it to the tag name itself, all you have to supply to git-flow is the 'release name'.

I have this working in my fork, and thanks to 'npm link' I am able to release now.  Let me know if you would be interested in a PR.

**Comment by mrkmg** [comment]
Would love a PR!

**Comment by matt328** [comment]
PR submitted which just removes versiontag altogether, although after considering usage outside of NodeJS projects, I might need to think about that some more.  I don't think it is valid to have prefixes on your version in package.json, but that isn't to say other types of projects won't want access to the prefixed version string for writing into tokenized files.  Your thoughts?

**Comment by mrkmg** [comment]
I will do some research in other package systems. Obviously it needs to change for NPM at least, so I will mostly likely accept the PR and then if needed add in special circumstances for other types of packages.

**Comment by mrkmg** [comment]
It appears that we really do not need the version tag for the couple things I looked into. Merged the PR.
